In [2]:
if 'google.colab' in str(get_ipython()):
    print('Running on CoLab')
    run_on_colab = True
else:
    print('Not running on CoLab')
    run_on_colab = False                                                                                                                                              
if run_on_colab:
    from google.colab import drive
    drive.mount('/drive', force_remount=True)

Running on CoLab
Mounted at /drive


In [3]:
!pip install ipython-autotime
%load_ext autotime

time: 216 µs (started: 2021-06-05 17:21:18 +00:00)


In [4]:
import pickle
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.externals import joblib
import matplotlib.pyplot as plt

time: 769 ms (started: 2021-06-05 17:21:18 +00:00)


/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [5]:
window_length=5
threshold=0.15
rocs=1
clf = None
scaler = None

time: 2.34 ms (started: 2021-06-05 17:21:20 +00:00)


In [7]:
train_df = pd.read_csv("/drive/My Drive/disertation/train_df_{}_rocs_{}.csv".format(threshold,rocs))
train_df = train_df.set_index("open_time")
train_df.drop(columns=["close"],inplace=True)
train_df

sma5_diff  sma8_diff  ...     RVI_14  output_class
open_time                                  ...                         
2017-08-17 04:33:00  -0.000882  -0.000402  ...  26.024920           0.0
2017-08-17 04:34:00   0.004152   0.005384  ...  58.444576           1.0
2017-08-17 04:35:00   0.004072   0.005260  ...  75.155465           1.0
2017-08-17 04:36:00   0.002876   0.004269  ...  75.155465           1.0
2017-08-17 04:37:00   0.001681   0.003138  ...  75.155465           1.0
...                        ...        ...  ...        ...           ...
2018-07-29 15:07:00   0.000561   0.000571  ...  56.326805           1.0
2018-07-29 15:08:00   0.000527   0.000675  ...  61.932170           1.0
2018-07-29 15:09:00   0.000366   0.000728  ...  66.525812           1.0
2018-07-29 15:10:00   0.000199   0.000586  ...  70.757193           1.0
2018-07-29 15:11:00   0.000391   0.000744  ...  74.700387           1.0

[498879 rows x 28 columns]

time: 4.51 s (started: 2021-06-05 17:21:42 +00:00)


In [8]:
train_df.index = pd.to_datetime(train_df.index)

time: 118 ms (started: 2021-06-05 17:21:48 +00:00)


In [9]:
data = train_df.to_numpy()
X = data[:,:-1]
Y = data[:,-1]

X.shape, Y.shape

((498879, 27), (498879,))

time: 10.5 ms (started: 2021-06-05 17:21:48 +00:00)


In [10]:
def extend_dataset_with_window_length(X, Y, window_length=5):
    new_x = []
    for i in range(len(X) - window_length+1):
        lst = []
        for j in range(i, i+window_length):
            lst.extend(X[j])
        new_x.append(lst)
    return np.array(new_x), Y[window_length-1:]

time: 4.89 ms (started: 2021-06-05 17:21:50 +00:00)


In [11]:
X, Y = extend_dataset_with_window_length(X,Y)
X.shape, Y.shape

((498875, 135), (498875,))

time: 31 s (started: 2021-06-05 17:21:51 +00:00)


In [12]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

time: 696 ms (started: 2021-06-05 17:22:22 +00:00)


In [13]:
scaler_path = "/drive/My Drive/disertation/scaler_logistic.save"
if scaler:
    joblib.dump(scaler, scaler_path)
else:
    scaler = joblib.load(scaler_path)

time: 12.9 ms (started: 2021-06-05 17:22:23 +00:00)


In [14]:
def get_subsample_same_distribution(X,Y, p=0.1):
    ys = pd.Series(Y)
    vs = ys.value_counts()
    original_indexes = []
    for idx in vs.index:
        required = int(p * vs[idx])
        print(required)
        original_indexes.extend(ys[ys==idx].sample(n=required, replace=False).index)
    return X[original_indexes], Y[original_indexes]

time: 8.19 ms (started: 2021-06-05 17:22:23 +00:00)


In [15]:
a,b = np.unique(Y, return_counts=True)
print("buy hold sell %")
print(b)
print(b / sum(b))

buy hold sell %
[ 60627 377448  60800]
[0.12152744 0.75659835 0.12187422]
time: 27.1 ms (started: 2021-06-05 17:22:23 +00:00)


In [16]:
def get_equal_class_distribution(X,Y):
    ys = pd.Series(Y)
    vs = ys.value_counts()
    required_of_each_class = vs.min()
    original_indexes = []
    for idx in vs.index:
        original_indexes.extend(ys[ys==idx].sample(n=required_of_each_class, replace=False).index)
    return X[original_indexes], Y[original_indexes]

time: 6.71 ms (started: 2021-06-05 17:22:23 +00:00)


In [17]:
X,Y = get_equal_class_distribution(X,Y)
#X, Y = get_subsample_same_distribution(X,Y)
a,b = np.unique(Y, return_counts=True)
print("buy hold sell %")
print(b)
print(b / sum(b))

buy hold sell %
[60627 60627 60627]
[0.33333333 0.33333333 0.33333333]
time: 188 ms (started: 2021-06-05 17:22:31 +00:00)


In [18]:
clf = LogisticRegression(n_jobs=-1, verbose=True, max_iter=10000)
clf.fit(X, Y)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:  8.2min finished


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=-1, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=True,
                   warm_start=False)

time: 8min 14s (started: 2021-06-05 17:22:47 +00:00)


In [22]:
clf.n_iter_

array([2076], dtype=int32)

time: 8.32 ms (started: 2021-06-05 17:32:00 +00:00)


In [20]:
print(clf.score(X, Y))
Y_train_predicted = clf.predict(X)

print(np.array(np.unique(Y, return_counts=True)).T)

a,b = np.unique(Y, return_counts=True)
print("buy hold sell %")
print(b / sum(b))

print(np.array(np.unique(Y_train_predicted, return_counts=True)).T)

a,b = np.unique(Y_train_predicted, return_counts=True)
print("buy hold sell %")
print(b / sum(b))

0.5254534558310104
[[0.0000e+00 6.0627e+04]
 [1.0000e+00 6.0627e+04]
 [2.0000e+00 6.0627e+04]]
buy hold sell %
[0.33333333 0.33333333 0.33333333]
[[0.0000e+00 5.2825e+04]
 [1.0000e+00 7.8779e+04]
 [2.0000e+00 5.0277e+04]]
buy hold sell %
[0.29043715 0.43313485 0.27642799]
time: 256 ms (started: 2021-06-05 17:31:01 +00:00)


In [21]:
Y_train_predicted = clf.predict(X)
print(metrics.confusion_matrix(Y, Y_train_predicted))

# Print the precision and recall, among other metrics
print(metrics.classification_report(Y, Y_train_predicted, digits=3))

[[27414 18228 14985]
 [ 9517 41987  9123]
 [15894 18564 26169]]
              precision    recall  f1-score   support

         0.0      0.519     0.452     0.483     60627
         1.0      0.533     0.693     0.602     60627
         2.0      0.520     0.432     0.472     60627

    accuracy                          0.525    181881
   macro avg      0.524     0.525     0.519    181881
weighted avg      0.524     0.525     0.519    181881

time: 708 ms (started: 2021-06-05 17:31:01 +00:00)


In [23]:
clf_file = "/drive/My Drive/disertation/logistic_regression_attempt_1_dataset_balanced.pickle"
if clf:
    pickle.dump(clf, open(clf_file, 'wb'))
else:
    clf = pickle.load(open(clf_file, "rb"))

time: 10.7 ms (started: 2021-06-05 17:33:51 +00:00)


In [27]:
tune_df = pd.read_csv("/drive/My Drive/disertation/tune_df_{}_rocs_{}.csv".format(threshold,rocs))
tune_df = tune_df.set_index("open_time")

tune_df.drop(columns="close", inplace=True)

data = tune_df.to_numpy()
X_tune = data[:,:-1]
Y_tune = data[:,-1]

X_tune, Y_tune = extend_dataset_with_window_length(X_tune, Y_tune)

time: 59.8 s (started: 2021-06-05 17:35:47 +00:00)


In [28]:
X_tune = scaler.transform(X_tune)

time: 651 ms (started: 2021-06-05 17:36:53 +00:00)


In [29]:
a,b = np.unique(Y_tune, return_counts=True)
print("buy hold sell %")
print(b / sum(b))
Y_tune_predicted = clf.predict(X_tune)
print(metrics.confusion_matrix(Y_tune, Y_tune_predicted))

print(metrics.classification_report(Y_tune, Y_tune_predicted, digits=3))


buy hold sell %
[0.03926218 0.9223085  0.03842931]
[[  9083  21213   8878]
 [ 26999 862216  31022]
 [  8193  21063   9087]]
              precision    recall  f1-score   support

         0.0      0.205     0.232     0.218     39174
         1.0      0.953     0.937     0.945    920237
         2.0      0.185     0.237     0.208     38343

    accuracy                          0.882    997754
   macro avg      0.448     0.469     0.457    997754
weighted avg      0.894     0.882     0.888    997754

time: 3.59 s (started: 2021-06-05 17:36:57 +00:00)


In [32]:
# clear ram
del tune_df
del X_tune
del Y_tune

NameError: ignored

time: 20.7 ms (started: 2021-06-05 17:38:42 +00:00)


In [33]:
test_df = pd.read_csv("/drive/My Drive/disertation/test_df_{}_rocs_{}.csv".format(threshold,rocs))
test_df = test_df.set_index("open_time")

test_df.drop(columns="close", inplace=True)

data = test_df.to_numpy()
X_test = data[:,:-1]
Y_test = data[:,-1]

X_test, Y_test = extend_dataset_with_window_length(X_test, Y_test)

time: 25.3 s (started: 2021-06-05 17:38:54 +00:00)


In [34]:
X_test = scaler.transform(X_test)

time: 346 ms (started: 2021-06-05 17:39:26 +00:00)


In [35]:
a,b = np.unique(Y_test, return_counts=True)
print("buy hold sell %")
print(b / sum(b))
Y_test_predicted = clf.predict(X_test)
print(metrics.confusion_matrix(Y_test, Y_test_predicted))

print(metrics.classification_report(Y_test, Y_test_predicted, digits=3))

buy hold sell %
[0.06405412 0.87312052 0.06282536]
[[ 13684   5619  12652]
 [ 77961 290281  67336]
 [ 14300   5332  11710]]
              precision    recall  f1-score   support

         0.0      0.129     0.428     0.198     31955
         1.0      0.964     0.666     0.788    435578
         2.0      0.128     0.374     0.190     31342

    accuracy                          0.633    498875
   macro avg      0.407     0.489     0.392    498875
weighted avg      0.858     0.633     0.713    498875

time: 1.9 s (started: 2021-06-05 17:39:26 +00:00)
